export const GET_ALL_COLLABORATORS_REQUEST = 'GET_ALL_COLLABORATORS_REQUEST'
export const GET_ALL_COLLABORATORS_SUCCESS = 'GET_ALL_COLLABORATORS_SUCCESS'
export const GET_ALL_COLLABORATORS_FAIL = 'GET_ALL_COLLABORATORS_FAIL'
export const GET_ALL_COLLABORATORS_RESET = 'GET_ALL_COLLABORATORS_RESET'

export const DELETE_COLLABORATOR_REQUEST = 'DELETE_COLLABORATOR_REQUEST'
export const DELETE_COLLABORATOR_SUCCESS = 'DELETE_COLLABORATOR_SUCCESS'
export const DELETE_COLLABORATOR_FAIL = 'DELETE_COLLABORATOR_FAIL'
export const DELETE_COLLABORATOR_RESET = 'DELETE_COLLABORATOR_RESET'

export const UPDATE_COLLABORATOR_REQUEST = 'UPDATE_COLLABORATOR_REQUEST'
export const UPDATE_COLLABORATOR_SUCCESS = 'UPDATE_COLLABORATOR_SUCCESS'
export const UPDATE_COLLABORATOR_FAIL = 'UPDATE_COLLABORATOR_FAIL'
export const UPDATE_COLLABORATOR_RESET = 'UPDATE_COLLABORATOR_RESET'
