export const GET_ALL_WAREHOUSES_REQUEST = 'GET_ALL_WAREHOUSES_REQUEST'
export const GET_ALL_WAREHOUSES_SUCCESS = 'GET_ALL_WAREHOUSES_SUCCESS'
export const GET_ALL_WAREHOUSES_FAIL = 'GET_ALL_WAREHOUSES_FAIL'
export const GET_ALL_WAREHOUSES_RESET = 'GET_ALL_WAREHOUSES_RESET'

export const DELETE_WAREHOUSE_REQUEST = 'DELETE_WAREHOUSE_REQUEST'
export const DELETE_WAREHOUSE_SUCCESS = 'DELETE_WAREHOUSE_SUCCESS'
export const DELETE_WAREHOUSE_FAIL = 'DELETE_WAREHOUSE_FAIL'
export const DELETE_WAREHOUSE_RESET = 'DELETE_WAREHOUSE_RESET'

export const UPDATE_WAREHOUSE_REQUEST = 'UPDATE_WAREHOUSE_REQUEST'
export const UPDATE_WAREHOUSE_SUCCESS = 'UPDATE_WAREHOUSE_SUCCESS'
export const UPDATE_WAREHOUSE_FAIL = 'UPDATE_WAREHOUSE_FAIL'
export const UPDATE_WAREHOUSE_RESET = 'UPDATE_WAREHOUSE_RESET'

export const CREATE_WAREHOUSE_REQUEST = 'CREATE_WAREHOUSE_REQUEST'
export const CREATE_WAREHOUSE_SUCCESS = 'CREATE_WAREHOUSE_SUCCESS'
export const CREATE_WAREHOUSE_FAIL = 'CREATE_WAREHOUSE_FAIL'
export const CREATE_WAREHOUSE_RESET = 'CREATE_WAREHOUSE_RESET'
